import type { Metadata } from "next";
import { neueMontreal, notoSansJp } from "./fonts";
import "./globals.css";
import PageTransition from "@/components/PageTransition";
import Menu from "@/components/Menu";
import { LanguageProvider } from "@/contexts/LanguageContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${neueMontreal.className}
          ${notoSansJp.variable}
          antialiased
          h-screen
          bg-[#D5D5D5]
        `}
      >
        <LanguageProvider>
          <Menu />
          <PageTransition>
            <div
              id="main-container"
              className="relative transform will-change-transform bg-[#D5D5D5]"
            >
              {children}
            </div>
          </PageTransition>
        </LanguageProvider>
      </body>
    </html>
  );
}
